// GENERATED BY tool/generate_tokens.dart — DO NOT EDIT.
// Source: design/tokens.css. Regenerate with `make tokens`.
//
// Every on*/status/connectivity pair here is verified >= 4.5:1 by the
// design set's contrast.mjs (130 pairs, 0 failures). Changing a value by
// hand bypasses that check — change tokens.css and regenerate instead.

import 'dart:ui';

import 'package:flutter/animation.dart' show Cubic;

/// The full colour role set for one theme.
class AlmanacColors {
  final Color background;
  final Color surface;
  final Color surfaceContainer;
  final Color surfaceContainerHigh;
  final Color onSurface;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color primary;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color tertiary;
  final Color onTertiary;
  final Color tertiaryContainer;
  final Color onTertiaryContainer;
  final Color inkSurface;
  final Color onInkSurface;
  final Color onInkSurfaceVariant;
  final Color inkHairline;
  final Color statusOnTrack;
  final Color statusOnTrackContainer;
  final Color onStatusOnTrackContainer;
  final Color statusNeedsAttention;
  final Color statusNeedsAttentionContainer;
  final Color onStatusNeedsAttentionContainer;
  final Color statusActionRequired;
  final Color statusActionRequiredContainer;
  final Color onStatusActionRequiredContainer;
  final Color connOffline;
  final Color connOfflineContainer;
  final Color onConnOfflineContainer;
  final Color connSyncing;
  final Color connSynced;
  final Color backdrop;
  final Color swatchRing;
  final Color deviceBezel;
  final Color glassSurface;
  final Color glassSurfaceHigh;
  final Color glassHairline;
  final Color glassHairlineStrong;
  final Color glassOnImagery;
  final Color glassOnImageryStrong;

  const AlmanacColors({
    required this.background,
    required this.surface,
    required this.surfaceContainer,
    required this.surfaceContainerHigh,
    required this.onSurface,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.inkSurface,
    required this.onInkSurface,
    required this.onInkSurfaceVariant,
    required this.inkHairline,
    required this.statusOnTrack,
    required this.statusOnTrackContainer,
    required this.onStatusOnTrackContainer,
    required this.statusNeedsAttention,
    required this.statusNeedsAttentionContainer,
    required this.onStatusNeedsAttentionContainer,
    required this.statusActionRequired,
    required this.statusActionRequiredContainer,
    required this.onStatusActionRequiredContainer,
    required this.connOffline,
    required this.connOfflineContainer,
    required this.onConnOfflineContainer,
    required this.connSyncing,
    required this.connSynced,
    required this.backdrop,
    required this.swatchRing,
    required this.deviceBezel,
    required this.glassSurface,
    required this.glassSurfaceHigh,
    required this.glassHairline,
    required this.glassHairlineStrong,
    required this.glassOnImagery,
    required this.glassOnImageryStrong,
  });
}

const almanacColorsLight = AlmanacColors(
  background: Color(0xFFF4F1EA),
  surface: Color(0xFFFBFAF6),
  surfaceContainer: Color(0xFFEDE9DF),
  surfaceContainerHigh: Color(0xFFE4DFD2),
  onSurface: Color(0xFF1C1B16),
  onSurfaceVariant: Color(0xFF4A473E),
  outline: Color(0xFF6F6B5F),
  outlineVariant: Color(0xFFCFC9BA),
  primary: Color(0xFF1D5233),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFC7E7D1),
  onPrimaryContainer: Color(0xFF0A2C18),
  secondary: Color(0xFF5A4630),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFEDDFC8),
  onSecondaryContainer: Color(0xFF2B2012),
  tertiary: Color(0xFF1A4E72),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFCFE4F3),
  onTertiaryContainer: Color(0xFF082D44),
  inkSurface: Color(0xFF1E1F1A),
  onInkSurface: Color(0xFFEFECE1),
  onInkSurfaceVariant: Color(0xFFB7B2A3),
  inkHairline: Color(0x24EFECE1),
  statusOnTrack: Color(0xFF18663A),
  statusOnTrackContainer: Color(0xFFC7E7D1),
  onStatusOnTrackContainer: Color(0xFF0A2C18),
  statusNeedsAttention: Color(0xFF8A5300),
  statusNeedsAttentionContainer: Color(0xFFFAE3BC),
  onStatusNeedsAttentionContainer: Color(0xFF432700),
  statusActionRequired: Color(0xFFA31C12),
  statusActionRequiredContainer: Color(0xFFFBD9D4),
  onStatusActionRequiredContainer: Color(0xFF4C0B06),
  connOffline: Color(0xFF455360),
  connOfflineContainer: Color(0xFFDCE3EA),
  onConnOfflineContainer: Color(0xFF1C2831),
  connSyncing: Color(0xFF1A4E72),
  connSynced: Color(0xFF18663A),
  backdrop: Color(0x851C1B16),
  swatchRing: Color(0x241C1B16),
  deviceBezel: Color(0xFF0C0D0A),
  glassSurface: Color(0xE6FBFAF6),
  glassSurfaceHigh: Color(0xEBEDE9DF),
  glassHairline: Color(0x1A1C1B16),
  glassHairlineStrong: Color(0x291C1B16),
  glassOnImagery: Color(0x9E12110E),
  glassOnImageryStrong: Color(0xBD12110E),
);

const almanacColorsDark = AlmanacColors(
  background: Color(0xFF000000),
  surface: Color(0xFF1A1B16),
  surfaceContainer: Color(0xFF232420),
  surfaceContainerHigh: Color(0xFF2C2E28),
  onSurface: Color(0xFFECE9DE),
  onSurfaceVariant: Color(0xFFC2BEAF),
  outline: Color(0xFF928D7E),
  outlineVariant: Color(0xFF4A4840),
  primary: Color(0xFF8ED3A3),
  onPrimary: Color(0xFF032E17),
  primaryContainer: Color(0xFF2A5740),
  onPrimaryContainer: Color(0xFFCAEFD6),
  secondary: Color(0xFFDCC49E),
  onSecondary: Color(0xFF2E2113),
  secondaryContainer: Color(0xFF4C3A25),
  onSecondaryContainer: Color(0xFFF0DEC2),
  tertiary: Color(0xFF8FCBEC),
  onTertiary: Color(0xFF032F48),
  tertiaryContainer: Color(0xFF22506E),
  onTertiaryContainer: Color(0xFFCBE6F7),
  inkSurface: Color(0xFF23241E),
  onInkSurface: Color(0xFFECE9DE),
  onInkSurfaceVariant: Color(0xFFC2BEAF),
  inkHairline: Color(0x24ECE9DE),
  statusOnTrack: Color(0xFF7ACB95),
  statusOnTrackContainer: Color(0xFF22503A),
  onStatusOnTrackContainer: Color(0xFFC3EBD1),
  statusNeedsAttention: Color(0xFFF0B855),
  statusNeedsAttentionContainer: Color(0xFF5A3E0B),
  onStatusNeedsAttentionContainer: Color(0xFFFBDFAE),
  statusActionRequired: Color(0xFFFF9186),
  statusActionRequiredContainer: Color(0xFF6B1C14),
  onStatusActionRequiredContainer: Color(0xFFFFD8D2),
  connOffline: Color(0xFFA9B7C5),
  connOfflineContainer: Color(0xFF333C45),
  onConnOfflineContainer: Color(0xFFD5DFE8),
  connSyncing: Color(0xFF8FCBEC),
  connSynced: Color(0xFF7ACB95),
  backdrop: Color(0xAD000000),
  swatchRing: Color(0x2EECE9DE),
  deviceBezel: Color(0xFF1C1D18),
  glassSurface: Color(0xE01A1B16),
  glassSurfaceHigh: Color(0xEB232420),
  glassHairline: Color(0x1FECE9DE),
  glassHairlineStrong: Color(0x33ECE9DE),
  glassOnImagery: Color(0x9E0A0B08),
  glassOnImageryStrong: Color(0xBD0A0B08),
);

/// Spacing, radii and layout. 4px base.
abstract final class AlmanacDimens {
  static const double sp1 = 4.0;
  static const double sp2 = 8.0;
  static const double sp3 = 12.0;
  static const double sp4 = 16.0;
  static const double sp5 = 20.0;
  static const double sp6 = 24.0;
  static const double sp7 = 32.0;
  static const double sp8 = 40.0;
  static const double sp9 = 48.0;
  static const double rXs = 8.0;
  static const double rSm = 12.0;
  static const double rMd = 16.0;
  static const double rLg = 20.0;
  static const double rXl = 28.0;
  static const double r2xl = 32.0;
  static const double rPill = 999.0;
  static const double rFrameInset = 8.0;
  static const double touchMin = 48.0;
  static const double gutter = 20.0;
  static const double navbarH = 64.0;
}

/// Motion. Durations collapse to 1ms under reduced motion — see AppMotion.
abstract final class AlmanacMotion {
  static const Duration durMicro = Duration(milliseconds: 180);
  static const Duration durScreen = Duration(milliseconds: 300);
  static const Duration durSheet = Duration(milliseconds: 380);
  static const Duration durHero = Duration(milliseconds: 400);
  static const Cubic easeStandard = Cubic(0.2, 0.0, 0.0, 1.0);
  static const Cubic easeEmphasised = Cubic(0.05, 0.7, 0.1, 1.0);
  static const Cubic easeExit = Cubic(0.3, 0.0, 1.0, 1.0);
}

/// One entry of the type scale, in logical pixels.
class AlmanacTypeToken {
  final int weight;
  final double size;
  final double lineHeight;
  const AlmanacTypeToken(this.weight, this.size, this.lineHeight);

  /// Flutter expects line height as a multiple of font size.
  double get heightFactor => lineHeight / size;
}

/// Type scale. Floor is 14px body / 13px meta — there is deliberately
/// no smaller token to reach for.
abstract final class AlmanacType {
  static const AlmanacTypeToken displayL = AlmanacTypeToken(400, 36.0, 40.0);
  static const AlmanacTypeToken headlineL = AlmanacTypeToken(600, 30.0, 36.0);
  static const AlmanacTypeToken headlineM = AlmanacTypeToken(600, 26.0, 32.0);
  static const AlmanacTypeToken headlineS = AlmanacTypeToken(600, 22.0, 28.0);
  static const AlmanacTypeToken titleL = AlmanacTypeToken(600, 20.0, 26.0);
  static const AlmanacTypeToken titleM = AlmanacTypeToken(600, 17.0, 24.0);
  static const AlmanacTypeToken titleS = AlmanacTypeToken(600, 15.0, 20.0);
  static const AlmanacTypeToken bodyL = AlmanacTypeToken(400, 16.0, 24.0);
  static const AlmanacTypeToken bodyM = AlmanacTypeToken(400, 15.0, 22.0);
  static const AlmanacTypeToken bodyS = AlmanacTypeToken(400, 14.0, 20.0);
  static const AlmanacTypeToken labelL = AlmanacTypeToken(600, 15.0, 20.0);
  static const AlmanacTypeToken labelM = AlmanacTypeToken(600, 14.0, 18.0);
  static const AlmanacTypeToken labelS = AlmanacTypeToken(600, 13.0, 16.0);
  static const AlmanacTypeToken numericXl = AlmanacTypeToken(600, 34.0, 38.0);
  static const AlmanacTypeToken numericL = AlmanacTypeToken(600, 24.0, 28.0);
  static const AlmanacTypeToken numericM = AlmanacTypeToken(600, 18.0, 22.0);
}
