import type { ArPoint, GpsPoint } from '../../src/index';

export const square20m: readonly ArPoint[] = [
  { x: 0, z: 0 },
  { x: 20, z: 0 },
  { x: 20, z: 20 },
  { x: 0, z: 20 },
];

export const figureEight: readonly ArPoint[] = [
  { x: 0, z: 0 },
  { x: 20, z: 20 },
  { x: 0, z: 20 },
  { x: 20, z: 0 },
];

// Mild positional noise on one straight side of a walked square.
export const shakyWalk: readonly ArPoint[] = [
  { x: 0, z: 0 },
  { x: 5, z: 0.08 },
  { x: 10, z: -0.08 },
  { x: 15, z: 0.08 },
  { x: 20, z: 0 },
  { x: 20, z: 20 },
  { x: 0, z: 20 },
];

// About 20 m per side near Johannesburg; fixed coordinates, not generated by the library.
export const gpsSquare: readonly GpsPoint[] = [
  { latitude: -26.02, longitude: 28.05, accuracyMetres: 3 },
  { latitude: -26.02, longitude: 28.0502, accuracyMetres: 3 },
  { latitude: -26.01982, longitude: 28.0502, accuracyMetres: 3 },
  { latitude: -26.01982, longitude: 28.05, accuracyMetres: 3 },
];
