"""Generate every API client artifact from the actual FastAPI application."""

import json
import shutil
import subprocess
from pathlib import Path

from farmable_backend.main import create_app

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "packages/api-client"


def main() -> None:
    pnpm = shutil.which("pnpm")
    if pnpm is None:
        raise RuntimeError("pnpm is required; run make setup")
    schema = create_app().openapi()
    (PACKAGE / "src").mkdir(exist_ok=True)
    (PACKAGE / "openapi.json").write_text(
        json.dumps(schema, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    subprocess.run(  # noqa: S603
        [
            pnpm,
            "exec",
            "openapi-typescript",
            "packages/api-client/openapi.json",
            "-o",
            "packages/api-client/src/schema.d.ts",
        ],
        cwd=ROOT,
        check=True,
    )
    (PACKAGE / "src/index.ts").write_text(
        "// Generated by make client. Do not edit.\n"
        'import createClient from "openapi-fetch";\n'
        'import type { paths } from "./schema";\n'
        'export type { paths, components, operations } from "./schema";\n'
        "export function createApiClient(baseUrl: string) {\n"
        "  return createClient<paths>({ baseUrl });\n"
        "}\n",
        encoding="utf-8",
    )
    subprocess.run(  # noqa: S603
        [pnpm, "exec", "prettier", "--write", "packages/api-client"], cwd=ROOT, check=True
    )


if __name__ == "__main__":
    main()
